// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzHqeQqi-CD-WAXOHiu7bZrOKfC89JunM',
    appId: '1:940224589028:android:24ded42bcf7ee51e2e50f1',
    messagingSenderId: '940224589028',
    projectId: 'attendance-6bf18',
    databaseURL: 'https://attendance-6bf18-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-6bf18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XkcMuN8WtheYs3K5sZ9Y8rhqhnP_Pgo',
    appId: '1:940224589028:ios:d1da1bc7831b8ce92e50f1',
    messagingSenderId: '940224589028',
    projectId: 'attendance-6bf18',
    databaseURL: 'https://attendance-6bf18-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-6bf18.appspot.com',
    androidClientId: '940224589028-ggkdk35eov73m0sui91a0h5i2754surr.apps.googleusercontent.com',
    iosClientId: '940224589028-u9kv2v1ng01e3g8p7hpf3h8bqtqsjmre.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
